version: "3.8"
services:
  pg:
    image: postgres
    environment:
      POSTGRES_PASSWORD: plunched-bot
      POSTGRES_USER: postgres
      POSTGRES_DB: plunched_bot
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    image: plunched_bot
    depends_on:
      - pg
    ports:
      - "4000:4000"
